<div class="row"><div class="col-md-8"><div class="form-group"><label>Tiêu đề *</label><input class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $post->title) }}">@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="col-md-4"><div class="form-group"><label>Slug *</label><input class="form-control @error('slug') is-invalid @enderror" name="slug" value="{{ old('slug', $post->slug) }}">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Danh mục</label><select class="form-control" name="category_id"><option value="">Không chọn</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $post->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
<div class="col-md-3"><div class="form-group"><label>Trạng thái *</label><select class="form-control" name="status">@foreach(['draft' => 'Nháp', 'published' => 'Xuất bản', 'archived' => 'Lưu trữ'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $post->status ?: 'draft') === $value)>{{ $label }}</option>@endforeach</select></div></div>
<div class="col-md-3"><div class="form-group"><label>Ngày xuất bản</label><input class="form-control" type="datetime-local" name="published_at" value="{{ old('published_at', optional($post->published_at)->format('Y-m-d\\TH:i')) }}"></div></div></div>
<div class="form-group"><label>Tóm tắt</label><textarea class="form-control" name="excerpt" rows="3">{{ old('excerpt', $post->excerpt) }}</textarea></div>
<div class="form-group"><label>Nội dung *</label><textarea class="form-control @error('content') is-invalid @enderror" name="content" rows="12">{{ old('content', $post->content) }}</textarea>@error('content')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="form-group"><label>Ảnh đại diện (URL)</label><input class="form-control" type="url" name="featured_image" value="{{ old('featured_image', $post->featured_image) }}"></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Meta title</label><input class="form-control" name="meta_title" value="{{ old('meta_title', $post->meta_title) }}"></div></div><div class="col-md-6"><div class="form-group"><label>Meta description</label><textarea class="form-control" name="meta_description" rows="2">{{ old('meta_description', $post->meta_description) }}</textarea></div></div></div>
